env:
  node: true
  shared-node-browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
rules:
  indent:
    - warn
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
  no-unused-vars:
    - warn
plugins:
- standard
