sudo: false
language: node_js
node_js:
  - "9"
branches:
  only:
  - develop
  - /^greenkeeper/.*$/
before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
 - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
workflows:
  version: 2
  workflow_name:
    jobs:
      - lockfile
      - job1:
          requires:
            - lockfile
install:
  - yarn install -W
script:
  - yarn build
